on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build-win

jobs:
  build-windows:
    name: Build Windows Release
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing nativefier
        run: npm install nativefier -g

      - name: Compiling to Windows
        env:
          QVAPAY_LINK: ${{ secrets.QVAPAY_LINK }}
        run: nativefier $QVAPAY_LINK QvaPay-win-x64 -p windows -a x64 --icon sources/qvapay.ico -n QvaPay --background-color "#5e72e4"

      - name: Compress all releases files
        run: tar.exe -a -c -f qvapay-windows-x64.zip QvaPay-win-x64 LICENSE

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            qvapay-windows-x64.tar.gz
